version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn intelect_kg.wsgi:application --bind ${APP_HOST}:${APP_PORT}
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data: